# Generated by Django 4.0.2 on 2022-02-26 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.IntegerField()),
                ('device_version', models.CharField(max_length=100)),
            ],
        ),
    ]
