# Generated by Django 4.0.2 on 2022-02-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_device_device_owner_device_device_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_status',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
    ]
