# Generated by Django 4.0.2 on 2022-02-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_device_device_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_data',
            field=models.CharField(default='0', max_length=2000),
        ),
    ]
